import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import api from '../api/axios.js';
import ProgressBar from '../components/ProgressBar.jsx';
import AiLessonAssist from '../components/AiLessonAssist.jsx';

export default function Learn() {
  const { courseId } = useParams();
  const [enrollment, setEnrollment] = useState(null);
  const [course, setCourse] = useState(null);
  const [activeLesson, setActiveLesson] = useState(null);
  const [loading, setLoading] = useState(true);
  const [marking, setMarking] = useState(false);
  const [aiCache, setAiCache] = useState({}); // lessonId -> { explanation, exercises }

  useEffect(() => {
    api.get('/enrollments/my-courses').then((res) => {
      const match = res.data.find((e) => e.course?._id === courseId);
      if (match) {
        setEnrollment(match);
        setCourse(match.course);
        const firstLesson = match.course?.modules?.[0]?.lessons?.[0];
        setActiveLesson(firstLesson || null);
      }
      setLoading(false);
    });
  }, [courseId]);

  const isCompleted = (lessonId) =>
    enrollment?.completedLessons?.some((id) => id === lessonId || id?._id === lessonId);

  // A lesson may already have AI content cached in the DB (generated by an
  // earlier student) — use that if present, otherwise fall back to whatever
  // was just generated this session.
  const getAiContent = (lesson) => {
    if (!lesson) return null;
    if (aiCache[lesson._id]) return aiCache[lesson._id];
    if (lesson.aiExplanation && lesson.aiExercises?.length) {
      return { explanation: lesson.aiExplanation, exercises: lesson.aiExercises };
    }
    return null;
  };

  const handleAiGenerated = (lessonId, content) => {
    setAiCache((prev) => ({ ...prev, [lessonId]: content }));
  };

  const handleMarkComplete = async () => {
    if (!activeLesson) return;
    setMarking(true);
    try {
      const { data } = await api.post(`/progress/${courseId}/lessons/${activeLesson._id}/complete`);
      setEnrollment((prev) => ({
        ...prev,
        completedLessons: data.completedLessons,
        progressPercent: data.progressPercent
      }));
    } catch (err) {
      console.error(err);
    } finally {
      setMarking(false);
    }
  };

  if (loading) return <div className="max-w-6xl mx-auto px-5 py-20 text-ink/40">Loading course...</div>;
  if (!course) {
    return (
      <div className="max-w-md mx-auto px-5 py-20 text-center">
        <p className="text-ink/60">You're not enrolled in this course, or it no longer exists.</p>
        <Link to="/dashboard" className="text-forest-700 underline mt-3 inline-block">Back to dashboard</Link>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto px-5 py-10 grid md:grid-cols-[280px_1fr] gap-8">
      <aside className="bg-white border border-forest-100 rounded-2xl p-5 h-fit md:sticky md:top-24">
        <h2 className="font-display font-semibold text-ink mb-1">{course.title}</h2>
        <div className="my-3">
          <div className="flex justify-between text-xs text-ink/50 mb-1.5">
            <span>Progress</span>
            <span>{enrollment?.progressPercent || 0}%</span>
          </div>
          <ProgressBar percent={enrollment?.progressPercent || 0} />
        </div>

        <div className="mt-4 space-y-4 max-h-[60vh] overflow-y-auto pr-1">
          {course.modules?.map((mod, mi) => (
            <div key={mod._id || mi}>
              <p className="text-xs font-semibold text-forest-700 uppercase tracking-wide mb-2">{mod.title}</p>
              <ul className="space-y-1">
                {mod.lessons?.map((lesson) => (
                  <li key={lesson._id}>
                    <button
                      onClick={() => setActiveLesson(lesson)}
                      className={`w-full text-left text-sm px-3 py-2 rounded-lg flex items-center gap-2 transition-colors ${
                        activeLesson?._id === lesson._id
                          ? 'bg-forest-50 text-forest-700 font-medium'
                          : 'text-ink/70 hover:bg-forest-50/60'
                      }`}
                    >
                      <span className={`w-4 h-4 rounded-full border flex-shrink-0 flex items-center justify-center text-[9px] ${
                        isCompleted(lesson._id) ? 'bg-sun-400 border-sun-400 text-forest-700' : 'border-ink/25'
                      }`}>
                        {isCompleted(lesson._id) && '✓'}
                      </span>
                      {lesson.title}
                    </button>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </aside>

      <section>
        <AnimatePresence mode="wait">
          {activeLesson && (
            <motion.div
              key={activeLesson._id}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -12 }}
              transition={{ duration: 0.25 }}
            >
              <div className="aspect-video bg-black rounded-2xl overflow-hidden">
                <iframe
                  src={activeLesson.videoUrl}
                  title={activeLesson.title}
                  className="w-full h-full"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  allowFullScreen
                />
              </div>

              <div className="flex items-center justify-between mt-5">
                <h2 className="font-display font-semibold text-xl text-ink">{activeLesson.title}</h2>
                <button
                  onClick={handleMarkComplete}
                  disabled={marking || isCompleted(activeLesson._id)}
                  className="text-sm font-medium bg-forest-700 text-white px-5 py-2.5 rounded-full disabled:opacity-50 whitespace-nowrap"
                >
                  {isCompleted(activeLesson._id) ? 'Completed ✓' : marking ? 'Saving...' : 'Mark as complete'}
                </button>
              </div>

              <AiLessonAssist
                courseId={courseId}
                lesson={activeLesson}
                content={getAiContent(activeLesson)}
                onGenerated={handleAiGenerated}
              />
            </motion.div>
          )}
        </AnimatePresence>
      </section>
    </div>
  );
}
